### PR TITLE
fix memory leak

### PR DESCRIPTION
**Pull request by TheRealSeq**

### CODE REVIEW

**Comment by StateFarmNetwork** [comment]
duplicate of https://github.com/Hydroflame522/StateFarmClient/pull/203

**Comment by VillainsRule** [comment]
@octocat ban this person from github, skidded my code from #203

**Comment by StateFarmNetwork** [comment]
@linus help pls fix

**Comment by StateFarmNetwork** [comment]
@StateFarmIns any ideas?

**Comment by StateFarmNetwork** [comment]
> one of those are actually going to see this in their notifications and be so confused

tim apple checking his notifs

**Comment by StateFarmNetwork** [comment]
> @BlueWizardDigital you might wanna check that one

wait what tf is that only 1 repo one hour ago?

**Comment by VillainsRule** [comment]
bad ping @wizardsupport

**Comment by VillainsRule** [comment]
gang can we close this shit its copyin me

**Pull request closed without merging**
