### PR TITLE
remove anti adblock

### PR DESCRIPTION
**Pull request by VillainsRule**
theres NO reason to make this a GUI setting.

### CODE REVIEW

**Comment by enbyte** [comment]
what? this should be toggleable and on by default

**Comment by OakSwingZZZ** [comment]
I already asked onlypuppy, and he said no options on by default and it should be toggled.

https://discord.com/channels/988104240000028706/1209747468300980264/1210355242982576128

**Comment by OakSwingZZZ** [comment]
> theres NO reason to make this a GUI setting.

Also, you completely ignored the existing code... I already made this feature. Look 25 lines down to the ad block that is in place. It will BREAK if you merge this. If you want to make it always on, change the existing code.

**Comment by onlypuppy7** [comment]
every feature is a module. theres no point in removing the ability to toggle things. things should be off be default in order not to cause crashes if something breaks and so that the user actually knows what the hell is going on

**Comment by onlypuppy7** [comment]
perhaps if this was just an aimbot with esp, then those options could be on by default but at this point its a do-it-all script rather than even a cheat

**Comment by OakSwingZZZ** [comment]
He also added already existing code. One thing you could do @onlypuppy7 is separate VIP spoof and adblock. But then that would make it hard to ALSO have Chicken Winner work.

**Comment by enbyte** [comment]
Push is useless, toggle does not need to be removed and this is a breaking change.

**Pull request closed without merging**
