### PR TITLE
pre10 - cheatchat replaces sfchat

### PR DESCRIPTION
**Pull request by VillainsRule**
also fixes fun eslint errors, as well as removes the 'guide' tab (which makes the ui generally look cleaner) (it wasn't used except for one module anyways)

### CODE REVIEW

**Comment by OakSwingZZZ** [comment]
No

**Comment by OakSwingZZZ** [comment]
POV: Replacing a service that has near 100% uptime that's not broken with one that has 30% uptime.

**Comment by Neuublue** [comment]
POV: in the stripped club.
straight up "jorking it".
and by "it", haha, well.

let's justr say. My peanits

**Comment by onlypuppy7** [comment]
this pr has many divisive changes for me, and most of this has now manually implemented into my next commit (didnt remove guides or sfchat)

**Pull request closed without merging**
